bookm/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('catalog/', include('books.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Library Management System' # default: "Django Administration"
admin.site.index_title = 'Welcome' # default: "Site administration"
admin.site.site_title = 'Book Catalog Admin' # default: "Django site admin"

books/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/signup/', views.RegisterView.as_view(), name='register'),
    path('user/profile/', views.profile, name='profile'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book.detail'),
    path('books/borrowed/', views.LoanedBooksByUserListView.as_view(), name='books.borrowed'),
    path('book/<uuid:pk>/borrow/', views.borrow_book_from_catalog, name='book.borrow'),
    path('book/<uuid:pk>/reserve/', views.reserve_book_from_catalog, name='book.reserve'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>',views.AuthorDetailView.as_view(), name='author.detail'),
]

books/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse 
import uuid
from datetime import date
from django.contrib.auth.models import User 
from . import helpers

class Category(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction, Fantasy, etc.)')
    
    class Meta:
        verbose_name = "Genre"
    
    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField('Full Name', max_length=100, default="Unknown")
    country = models.CharField(max_length=100)
    date_of_birth = models.DateField('Birthdate',null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['name', 'country']

    def get_absolute_url(self):
        return reverse('author.detail', args=[str(self.id)])

    def __str__(self):
        return self.name
    
    
class Book(models.Model):
    title = models.CharField('Title', max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    isbn = models.CharField(
        'ISBN', 
        max_length=17,
        default='000-0-00-000000-0', 
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Category, help_text='Select a genre for this book')
    lang = models.CharField('Language', default='English', max_length=100)
    edition = models.CharField('Edition', null=True, blank=True, max_length=100, help_text="Optional: You can specify the book edition")
    publisher = models.CharField('Publisher', null=True, blank=True, max_length=100, help_text="Optional: You can specify the book publisher ")    
    pub_date = models.CharField('Published', max_length=50, default="2021")
    summary = models.TextField(null=True, blank=True, max_length=1000, help_text='Enter a brief description of the book')
    
    
    class Meta:
        ordering = ['title', 'author']
            
    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book.detail', args=[str(self.id)])


class IssuedBook(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    issued_date = models.DateField('issued date', null=True, blank=True)
    expiry_date = models.DateField('due date', null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    @property
    def is_overdue(self):
        if self.expiry_date and date.today() > self.expiry_date:
            return True
        return False
    options = (
        ('m', 'MAINTENANCE'),
        ('o', 'LOANED'),
        ('a', 'AVAILABLE'),
        ('r', 'RESERVED'),
    )

    status = models.CharField(
        max_length=1,
        choices=options,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['issued_date','expiry_date']
        permissions = (("can_mark_returned", "Set book as returned"),)
        verbose_name_plural = "Catalog"

    def __str__(self):
        return f'{self.id} ({self.book.title})'
    

books/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError

class ReserveBookForm(forms.Form):
    start_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
    def clean_start_date(self):
        date = self.cleaned_data['start_date']
        
        # Check if a date is not in the past.
        if date < datetime.date.today():
            raise ValidationError(_('Invalid date - start in past'))
        
        # Check if a date is in the allowed range (+4 weeks from today).
        if date > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - start date more than 4 weeks ahead'))
        
        return date
    

books/views.py
from datetime import datetime, timedelta
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Book, Author, IssuedBook, Category
from .helpers import get_expiry_date
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .forms import ReserveBookForm

def home(request):
    # Generate counts of some of the main objects
    num_books = IssuedBook.objects.all().count()

    # Available books (status = 'a')
    num_books_available = IssuedBook.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    num_genres = Category.objects.count()
    
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books': num_books,
        'num_instances_available': num_books_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_visits': num_visits
    }
    
    return render(request, 'catalog/welcome.html', context)

def profile(request):
    context = {
        'message' : 'This is the catalog current user profile',
    }
    return render(request, 'catalog/profile.html', context)

def index(request):
    context = {
        'message' : 'This is catalog book index page',
    }
    return render(request, 'catalog/index.html', context)

class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

class BookListView(generic.ListView):
    """Generic class-based view for a list of books."""
    model = Book
    template_name = 'catalog/book_list.html'
    paginate_by = 50

class BookDetailView(generic.DetailView):
    """Generic class-based detail view for a book."""
    model = Book
    template_name = 'catalog/book_detail.html'

class AuthorListView(generic.ListView):
    """Generic class-based list view for a list of authors."""
    model = Author
    template_name = 'catalog/author_list.html'
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    """Generic class-based detail view for an author."""
    model = Author
    template_name = 'catalog/author_detail.html'

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    login_url = 'login'
    model = IssuedBook
    template_name ='catalog/user_borrowed_books.html'
    paginate_by = 10

    def get_queryset(self):
        return IssuedBook.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('expiry_date')

def borrow_book_from_catalog(request, pk):
     book_instance = get_object_or_404(IssuedBook, pk=pk)
     
     if request.method == 'POST':
        if book_instance.status == 'a':
             book_instance.issued_date = datetime.now()
             book_instance.expiry_date =  get_expiry_date()
             book_instance.status = 'o'
             book_instance.borrower = request.user
             book_instance.save()
        
     return HttpResponseRedirect(reverse('books.borrowed'))

def reserve_book_from_catalog(request, pk):
    book_instance = get_object_or_404(IssuedBook, pk=pk)

    if request.method == 'POST':

        form = ReserveBookForm(request.POST)

        if form.is_valid() and book_instance.status == 'a':
            book_instance.issued_date = form.cleaned_data['start_date']
            book_instance.expiry_date = form.cleaned_data['start_date'] + timedelta(weeks=3)
            book_instance.status = 'r'
            book_instance.borrower = request.user
            book_instance.save()
            
            return HttpResponseRedirect(reverse('books.borrowed') )

    elif book_instance.status == 'a':
        proposed_date = datetime.today() + timedelta(weeks=3)
        form = ReserveBookForm(initial={'start_date': proposed_date})

        context = {
            'form': form,
            'book_instance': book_instance,
        }

        return render(request, 'catalog/reserve_catalog_book.html', context)
    
    else:
        return HttpResponseRedirect(reverse('books.borrowed'))
         

books/templates/catalog/author_detail.html
{% extends "base.html" %}
{% block title %} Library {% endblock %}
{% block header %}
<h1 class="display-5 fw-bolder text-white mb-2">Author Detail</h1>
<p class="lead text-white-50 mb-4">
    {{ author }}
</p>
{% endblock %} 
{% block content %}
<section class="py-5 border-bottom" id="features">
    <div class="container px-5 my-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-12">
            <h1>Author: {{ author }} </h1>
            <p>{% if author.date_of_birth %} {{author.date_of_birth}}{% endif %} {% if author.date_of_death %} - {{author.date_of_death}}{% endif %}</p>

            <div style="margin-left:20px;margin-top:20px">
            <h4>Books</h4>

            <dl>
            {% for book in author.book_set.all %}
            <dt><a href="{% url 'book.detail' book.pk %}">{{book}}</a> ({{book.issuedbook_set.all.count}})</dt>
            <dd>{{book.summary}}</dd>
            {% endfor %}
            </dl>

            </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}

books/templates/catalog/author_list.html
{% extends "base.html" %}
{% block title %} Library {% endblock %}
{% block header %}
<h1 class="display-5 fw-bolder text-white mb-2">Our Best-Selling Authors</h1>
<p class="lead text-white-50 mb-4">
  A rich library with all genres of books, lists, bibliographies and reviews of library materials.
</p>
{% endblock %} 
{% block content %}
<section class="py-5 border-bottom" id="features">
    <div class="container px-5 my-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-12">
            <h1>Author List</h1>
            {% if author_list %}
            <ul>
            {% for author in author_list %}
                <li>
                <a href="{{ author.get_absolute_url }}">
                {{ author }} ({{author.country}})
                </a>
                </li>
            {% endfor %}
            </ul>
            {% else %}
            <p>There are no authors available.</p>
            {% endif %}
        </div>
        {% if is_paginated %}
        <div class="col-12">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                    {% endif %}
                </span>
            </div>
        </div>
       {% endif %}        
      </div>
    </div>
</section>
{% endblock %}

books/templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Book Manager</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/css/general.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          <ul class="sidebar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="#">All books</a></li>
            <li><a href="#">All authors</a></li>
          </ul>

          <ul class="sidebar-nav">
            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
            <li>
              <a href="{% url 'logout'%}?next={{request.path}}">Logout</a>
            </li>
            {% else %}
            <li><a href="{% url 'login'%}">Login</a></li>
            {% endif %}
          </ul>

          {% if user.is_staff %}
          <hr />
          <ul class="sidebar-nav">
            <li>Staff</li>
            {% if perms.catalog.can_mark_returned %}
            <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
            {% endif %}
          </ul>
          {% endif %} 
          {% endblock %}
        </div>
        <div class="col-sm-10 p-5 m-5">
          {% block content %}{% endblock %} 
          {% block pagination %} 
          {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
              {% if page_obj.has_previous %}
              <a
                href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
                >previous</a
              >
              {% endif %}
              <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages
                }}.
              </span>
              {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"
                >next</a
              >
              {% endif %}
            </span>
          </div>
          {% endif %} 
        {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

books/templates/catalog/book_detail.html
{% extends "base.html" %}
{% block title %} Library {% endblock %}
{% block header %}
<h1 class="display-5 fw-bolder text-white mb-2">Book Detail</h1>
<p class="lead text-white-50 mb-4">
    {{ book.title }}
</p>
{% endblock %}
{% block content %}
<section class="py-5 border-bottom" id="features">
    <div class="container px-5 my-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-12">
            <h1>Title: {{ book.title }}</h1>
            <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
            <p><strong>Summary:</strong> {{ book.summary }}</p>
            <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
            <p><strong>Language:</strong> {{ book.lang }}</p>  
            <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>
            <h4 class="mt-5">Book Copies ({{ book.issuedbook_set.all.count }})</h4>
            <div class="ml-5 pl-5">
            {% for copy in book.issuedbook_set.all %}
                <hr>
                <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
                {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.expiry_date}}</p>{% endif %}
                <p><strong>Imprint:</strong> {{copy.imprint}}</p>
                <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
                {% if user.is_authenticated and copy.status == 'a' %}
                   <div class="text-end" role="group" aria-label="Actions">
                    <button type="button" class="btn btn-sm btn-success"  data-bs-toggle="modal" data-bs-target="#borrowModal{{copy.id}}">Borrow</button>
                    <a href="{% url 'book.reserve' pk=copy.id %}" class="btn btn-sm btn-danger">Reserve</a>
                  </div>
                    <!-- Modal -->
                    <div class="modal fade" id="borrowModal{{copy.id}}" tabindex="-1" aria-labelledby="borrowModalLabel{{copy.id}}" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="borrowModalLabel{{copy.id}}">Borrow Book</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                             <p>Are sure you want to borrow {{ book.title }} by {{ book.author }}?</p>
                             <form id="modalForm{{copy.id}}" method="POST" action="{% url 'book.borrow' pk=copy.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="issued" value="{{copy.id }}"/>
                             </form>
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-sm btn-danger" data-bs-dismiss="modal">Cancel</button>
                            <button type="button" class="btn btn-sm btn-success" onclick="document.getElementById('modalForm{{copy.id}}').submit()">Confirm</button>
                            </div>
                        </div>
                        </div>
                    </div>                  
                {% endif %}
            {% endfor %}
            </div>
        </div>
      </div>
    </div>
</section>
{% endblock %} 

books/templates/catalog/book_list.html
{% extends "base.html" %}
{% block title %} Library {% endblock %}
{% block header %}
<h1 class="display-5 fw-bolder text-white mb-2">Books We Have</h1>
<p class="lead text-white-50 mb-4">
  A rich library with all genres of books, lists, bibliographies and reviews of library materials.
</p>
{% endblock %} 
{% block content %}
<section class="py-5 border-bottom" id="features">
    <div class="container px-5 my-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-12">
            <h1>Library</h1>
            {% if book_list %}
                <ul>
                    {% for book in book_list %}
                    <li>
                        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
               <p>There are no books in the library yet.</p>
            {% endif %} 
        </div>
        {% if is_paginated %}
        <div class="col-12">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                    {% endif %}
                </span>
            </div>
        </div>
       {% endif %}
      </div>
    </div>
</section>      
{% endblock %}

books/templates/catalog/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.last_name }} {{ user.first_name }} ({{ user.username }})!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

books/templates/catalog/reserve_catalog_book.html
{% extends "base.html" %}
{% block title %} Reserve Book {% endblock %}
{% block header %}
<h1 class="display-5 fw-bolder text-white mb-2">Reserve A Book</h1>
<p class="lead text-white-50 mb-4">
    {{ book.title }}
</p>
{% endblock %}
{% block content %}
<section class="py-5 border-bottom" id="features">
    <div class="container px-5 my-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-12">
            <h1>Reserve: {{book_instance.book.title}}</h1>
            <p>Borrower: {{user}}</p>
            <p>ID: {{book_instance.id}}</p>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="submit-row">
                    <button type="submit" class="btn btn-dark text-end">Reserve</button>
                </div>
            </form>
        </div>
      </div>
    </div>
</section>
{% endblock %}

books/templates/catalog/user_borrowed_books.html
{% extends "base.html" %}
{% block title %} My Borrowed Books {% endblock %}
{% block header %}
<h1 class="display-5 fw-bolder text-white mb-2">My Borrowed Books</h1>
{% endblock %} 
{% block content %}
<section class="py-5 border-bottom" id="features">
    <div class="container px-5 my-5">
      <div class="row gx-5 justify-content-center">
        <div class="col-12">
            <h1>Borrowed ({{ issuedbook_list | length }})</h1>
            {% if issuedbook_list %}
            <ul>
                {% for issued in issuedbook_list %}
                <li class="{% if issued.is_overdue %}text-danger{% endif %}">
                  <a href="{% url 'book.detail' issued.book.pk %}">{{issued.book.title}}</a> ({{ issued.expiry_date }})
                  {% if issued.is_overdue %} - OVERDUE{% endif %}
                </li>
                {% endfor %}
              </ul>
            {% else %}
               <p>You have no borrowed books from the library yet.</p>
            {% endif %} 
        </div>
        {% if is_paginated %}
        <div class="col-12">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                    {% endif %}
                </span>
            </div>
        </div>
       {% endif %}
      </div>
    </div>
</section>      
{% endblock %}

books/templates/catalog/welcome.html
{% extends 'base.html' %} 

{% block title %} Welcome {% endblock %}

{% block header %}
<h1 class="display-5 fw-bolder text-white mb-2">
  The World's Largest &amp; Rich Library Catalog
</h1>
<p class="lead text-white-50 mb-4">
  Discover the best books to read right now including trending titles,
  bookseller recommendations, new releases and more.
</p>
<div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
  <a  class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'login' %}">Login</a>
  <a class="btn btn-outline-light btn-lg px-4" href="{% url 'register' %}">Sign up</a>
</div>
{% endblock %} 

{% block content %}
<!-- Features section-->
<section class="py-5 border-bottom" id="features">
  <div class="container px-5 my-5">
    <div class="row gx-5">
      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3">
          <i class="bi bi-book"></i>
        </div>
        <h2 class="h4 fw-bolder">{{ num_books }}+ Books</h2>
        <p>
          Paragraph of text beneath the heading to explain the heading. We'll
          add onto it with another sentence and probably just keep going until
          we run out of words.
        </p>
        <a class="text-decoration-none" href="#!">
          Read more
          <i class="bi bi-arrow-right"></i>
        </a>
      </div>
      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3">
          <i class="bi bi-person"></i>
        </div>
        <h2 class="h4 fw-bolder">{{ num_authors }}+ Best-Selleing Authors</h2>
        <p>
          Paragraph of text beneath the heading to explain the heading. We'll
          add onto it with another sentence and probably just keep going until
          we run out of words.
        </p>
        <a class="text-decoration-none" href="#!">
          Read more
          <i class="bi bi-arrow-right"></i>
        </a>
      </div>
      <div class="col-lg-4">
        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3">
          <i class="bi bi-collection"></i>
        </div>
        <h2 class="h4 fw-bolder">{{ num_genres }}+ Book Genres</h2>
        <p>
          Paragraph of text beneath the heading to explain the heading. We'll
          add onto it with another sentence and probably just keep going until
          we run out of words.
        </p>
        <a class="text-decoration-none" href="#!">
          Read more
          <i class="bi bi-arrow-right"></i>
        </a>
      </div>
    </div>
  </div>
</section>
{% endblock %}